apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data
  labels:
    app.kubernetes.io/name: openldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config
  labels:
    app.kubernetes.io/name: openldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
