apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-data
  labels:
    app.kubernetes.io/name: mailserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-state
  labels:
    app.kubernetes.io/name: mailserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
